theme:
  name: material
  palette:
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/BodenmillerGroup/ImagingDevelopersMeeting2023
repo_name: BodenmillerGroup/ImagingDevelopersMeeting2023

use_directory_urls: false

plugins:
  - search

site_name: Multiplexed Image Analysis Developers Meeting
nav:
    - Home: index.md
    
markdown_extensions:
    - footnotes
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg